### ISSUE TITLE
Ignore directory and all nested directories/files

### ISSUE THREAD

**Issue by markreg** [pilu/fresh#50]
Adding a directory to the `ignored` list does not make `fresh` ignore all nested directories/files.

**Comment by wubin1989** [comment]
Yes, I found the same problem. Anyone can help to fix it?

**Comment by drKnoxy** [comment]
ugh

**Comment by gmccue** [comment]
@wubin1989 are you using a proper `recompile.conf` file? I had the same issue, but it seems to be resolved after setting the proper `root` and `ignore` lines in `recompile.conf`. 

My `recompile.conf` file for reference:
```
root:              .
tmp_path:          .tmp_build
build_name:        my-app
build_log:         my-app-build-errors.log
valid_ext:         .go, .tmpl
ignored:           assets, node_modules, vendor, vm, wraith
build_delay:       600
colors:            1
log_color_main:    cyan
log_color_build:   yellow
log_color_runner:  green
log_color_watcher: magenta
```

I start the binary with the following command within a Docker container:
```
backend:
  build: ./backend
  container_name: backend
  working_dir: /go/src/github.com/my-org/my-project
  command: fresh -c /go/src/github.com/my-org/my-project/containers/backend/recompile.conf
  env_file: ../../.env
  volumes:
   - ../../.:/go/src/github.com/my-org/my-project
  ports:
   - "8000:3001"
  links:
   - cache
```

**Comment by cristian-sima** [comment]
![image](https://cloud.githubusercontent.com/assets/12199042/16620936/0c7e1c9a-439d-11e6-8767-bb07d45b534b.png)

**Comment by cristian-sima** [comment]
So, the idea is that is ignoring that directory, but it watches all the sub directories

**Comment by gmccue** [comment]
@cristian-sima can you paste your `recompile.conf` ?

**Comment by cristian-sima** [comment]
Sure. I called it `fresh.conf`

root:              .
tmp_path:          tmp
build_name:        cube
build_log:         cube-build-errors.log
valid_ext:         .go, .tmpl
ignored:           tmp, node_modules, util, static, source, conf, grunt
build_delay:       600
colors:            1
log_color_main:    cyan
log_color_build:   yellow
log_color_runner:  green
log_color_watcher: magenta

**Comment by cristian-sima** [comment]
Thanks for your quick reply.  I was searching for an alternative to this project cause I can not do `npm install` in the sense it blocks the node folders

**Comment by cristian-sima** [comment]
@pilu  or someone else can take a look at this?

It is really frustrating :angry:

**Comment by cristian-sima** [comment]
Someone?

**Comment by pilu** [comment]
Hi @cristian-sima , I'm sorry for the late reply. Unfortunately I can't work on this soon, but it might be a quick fix for anyone who wants to send my a PR. 
There's a function called `isIgnoredFolder` in `utils.go` that checks that. It should be easy to change the `== paths[0]` to just check if a folder is a subfolder of the ignored path. maybe @ernestas-poskus that worked on that can help us?

**Comment by cristian-sima** [comment]
@pilu I solved this problem with the pull request

**Comment by gmccue** [comment]
Fixed by #60

**Comment by yoesoff** [comment]
I'm still having this issue, this is my conf:

  ```
root:              .
  tmp_path:          ./tmp
  build_name:        runner-build
  build_log:         runner-build-errors.log
  valid_ext:         .go 
  no_rebuild_ext:    .tpl, .tmpl, .html
  ignored:           assets, tmp, public/assets, vendor, templates, node_modules
  build_delay:       600
  colors:            1   
  log_color_main:    cyan
  log_color_build:   yellow
  log_color_runner:  green
  log_color_watcher: magenta
  log_color_app:
 
```

![image](https://user-images.githubusercontent.com/241982/29750431-b2e25a32-8b69-11e7-91d4-295cf1238890.png)


can comebody tell me how to fix it ?

**Comment by cheddarwhizzy** [comment]
I also can't ignore subdirectories with a '/' in the name (ie public/assets). I'll see if I can get this squared away

**Comment by trinode** [comment]
@gmccue should I open a new issue (since this is closed) as I'm experiencing what @cheddarwhizzy is, in my case I can ignore frontend, but not frontend/node_modules

**Comment by aequasi** [comment]
Can this get re-opened @markreg
